#+title: dotmg
#+author: Amrit
#+description: A $HOME manager.

* Introduction

This is a simple shell script that automates the generation
of a ~.gitignore~ file in a (optionally user specified) home
directory to make it easier for those who keep their ~$HOME~
as a git repository and bother with manually adding/removing
listings.

* Installation

** Default Install

This dotmg installs to ~/usr/bin~ 
#+BEGIN_SRC
# make install
#+END_SRC

** Different Prefix

#+BEGIN_SRC
# PREFIX=/usr/local make install
#+END_SRC

** Specify destination directory

This is useful for package managers or installing to a non-~/~ (root) directory.

#+BEGIN_SRC
$ DESTDIR=$HOME/.local/ PREFIX=/usr/bin make install
#+END_SRC

#+BEGIN_QUOTE
The ~uninstall~ target works the same way as the install target but deletes the
~dotmg~ script.
#+END_QUOTE

* Commands

- ~dotmg add file[s]|directory[ies]~: Add the specified arg
	to not be ignored by ~git~.
- ~dotmg init~: Initialises a git repository in ~$HOUSE~.
	Writes a base ~.gitignore~ that ignores everything in that
	directory.
- ~dotmg init-gitignore~: Writes only a base ~.gitignore~ in
	current directory.
-  ~dotmg clean-newlines~: Cleans up any empty newlines that
	may be present in ~.gitignore~ in the current directory.

* Details

** What is ~$HOUSE~?
This is an optionally user-set environment variable that dotmg
takes into account. If not specified, it defaults to ~$HOME~.

This ~$HOUSE~ directory is where ~dotmg~ always operates with
~init-gitignore~ and ~clean-newlines~ commands being exceptions.
They look for a ~.gitignore~ in the current directory.

* Work in Progress
- [ ] More error checking.
- [ ] Build system that installs the script.
- [ ] Manual Pages
